### ISSUE TITLE
Mistake in Remark 1.7.6

### ISSUE THREAD

**Issue by BastiaanCnossen** [Nicholas42/AlgebraFranke#1]
Hi there! I think the product \rad(I) \cdot \rad(J) in the second equation of remark 1.7.6 (of the script of Algebra I) should be the intersection \rad(I) \cap \rad(J). Otherwise the statement is false: see for example https://math.stackexchange.com/questions/1965296/is-the-radical-of-the-product-of-ideals-equal-to-the-product-of-the-radicals.

**Comment by Nicholas42** [comment]
Thanks for informing us. It will be fixed in the next update.
