### ISSUE TITLE
Exam with Franke

### ISSUE THREAD

**Issue by MarioF2** [Nicholas42/AlgebraFranke#10]
Hello!

I have the exam of Algebra II next week and the amount of contents of the subject is exhausting. Could you give me some info about how exams with Franke are?

Regards!

**Comment by Nicholas42** [comment]
Hello,

I am sorry, but I don't think, I can give you any helpful hints. I already had two exams by Professor Franke, but both of them were written ones while the Algebra II exam is an oral one, so I have no idea, how this will be.

Best Wishes

Nicholas
