### ISSUE TITLE
Quasi-compactness is not sufficient in proof of proposition 2.1.4!

### ISSUE THREAD

**Issue by BastiaanCnossen** [Nicholas42/AlgebraFranke#11]
Hi guys,
In the proof of the equivalent conditions for a prescheme X to be _integral_, we showed that under the assumption that X is Noetherian, the fact that the stalks are domains implies that X is irreducible. In a remark below the proof you said that we did not use finiteness of the number of irreducible components in the proof and so the proof also works with just the assumption of quasi-compactness. (Note already that quasi-compactness was only used to get the closed point, so that means that (d) would imply (a) without any extra condition.)
However, this is _not_ true. It can easily happen that the maximal irreducible components of a space are _setwise_ disjoint but not _topologically_ disjoint. Think for example of any Hausdorff space, like R. The maximal irreducible subsets are just points and they are disjoint, but still R is connected but not irreducible. The fact that there are infinitely many irreducible subsets makes it possible in R to still have a topology in which everything is connected.
In fact, if you look on the last exercise sheet, the final question was exactly to give a counterexample for your claim: to find an affine prescheme (so in particular q.c.) that is connected and has domains as stalks but is not irreducible.
I guess this comment won't help you personally as you probably already did the exam, but I think it would still be helpful for others to say something about this in your script.
Best,
Bastiaan

**Comment by FlorianAdler** [comment]
You are completely right, if not to say "Absolutely!", as Franke would probably phrase it ;). Thanks a lot for pointing this out.
