### ISSUE TITLE
Theorem 20, a shortcut?

### ISSUE THREAD

**Issue by jckt** [Nicholas42/AlgebraFranke#12]
(This is Thm 20 for Alg II)

For step 1, the length is eventually constant, so for some big enough k we know that I^kM = I^(k+1)M, right? Then by a slightly more general Nakayama lemma (instead of the Jacobson radical, replace it with any ideal contained within the Jacobson radical), since I is contained in the unique maximal ideal m of R, we should be done, right? For then you know that I^kM = 0, hence length of M is finite, hence M is Artin, hence dimension of M is zero.

But I'm really bad at maths so I'm probably missing something.

**Comment by FlorianAdler** [comment]
Nice proof! I replaced my original one in the lecture notes.
