### ISSUE TITLE
typography & typos

### ISSUE THREAD

**Issue by bforras** [Nicholas42/AlgebraFranke#14]
Hey guys,

many thanks for typing these notes, they are far superior to my hand-written ones.
I have gathered a couple of suggestions for improvement (most of them are just typos) for the Algebra II notes:

1) Spacing after dots: LaTeX automatically typesets spaces after dots to be somewhat bigger than the standard inter-word spacing, but this feature should only be used for full stops. After abbreviations such as e.g. or i.e. extra spacing is unnecessary and regarded by some as confusing for readers; to avoid it, one needs to put a \ after the dot and before the space. Or you might consider not using any extra spacing at all: this so-called French spacing technique can be adapted by invoking the creatively named command \frenchspacing in the preamble.

2) It seems that you used \mod in the formulas involving the class of an element modulo some ideal. Actually, \mod produces an unnecessarily (and some would say unappealingly) large gap before mod; this can be prevented by switching to \bmod.

3) The already great usability of the notes could potentially be slightly improved by changing the header to indicate not only the section but also the subsection number. This would be useful with the references for previous statements. I know, this is not an issue if one reads the notes on a computer or tablet but some, including myself, prefer printed notes.

4) Proof of Theorem 17: it should be p_x in the numerator.
5) In Remark 3.5.1.(b) one should write min instead of max.
6) In the proof of Proposition 1.4.1.: $d_{A/R}\in \Der_R(A,M)$ should be $d_{A/R}\in \Der_R(A,\Omega_{A/R})$ (line 625). Also, before "Let $(A\morphism[d] M)\in \Der_R(A,M)$.", one could perhaps insert "Let $M$ be an $A$-module."
7) Introduction: Zariski-topology →‎ Zariski topology
8) NAK: ba →‎ be. Also here: Cramers rule →‎ Cramer's rule.
9) Remark after Corollary 1.4.1: occuring →‎ occurring (multiple occurrences)
10) Just before Corollary 1.5.1: prize →‎ price, post-poning →‎ postponing.
11) Lemma 1.6.2: noetherian →‎ Noetherian
12) You seem to be using two different spellings for the same word: homogeneous and homogenous. It is probably best to stick to just one (my choice would be homogeneous.)
13) Corollary 2.3.1: Zariski-continous →‎ Zariski-continuous
14) Remark 3.1.1: Artin-Schreier →‎ Artin--Schreier, similarly for Akizuki-Hopkins, Artin-Rees, Cayley-Hamilton (multiple occurrences)
15) Proof of Theorem 18: finity type →‎ finite type.
16) Proposition 3.2.1: every graded $R$ on which $S$ acts invertibly module is obtained in this fashion →‎ every graded $R$-module on which $S$ acts invertibly is obtained in this fashion
17) After Definition 3.3.1: Explicitely → Explicitly
18) Corollary 3.4.2: associatd → associated
19) Corollary 3.4.7: Appyling → Applying
20) Proof of Theorem 21: satisifies → satisfies (multiple occurrences)
21) Theorem 23: muliplicities → multiplicities
22) Example after Theorem 23: staight → straight
23) Remark A.4.1: characteristizes → characterizes
24) Comment before Definition A.5.3: appearence → appearance

**Comment by FlorianAdler** [comment]
Thanks a lot for pointing out all that typos and the typographical suggestions (I wasn't even aware of how difficult English can get when it comes to hyphens and dashes). I also changed the header to subsections instead of sections.
Have a nice holiday
Ferdinand
