### ISSUE TITLE
typos in the Algebraic Geometry I script

### ISSUE THREAD

**Issue by bforras** [Nicholas42/AlgebraFranke#15]
Hey guys, I believe to have found a few minor typos in the Algebraic Geometry I script. Given the fact that after the first few weeks I did not attend the lectures, the likelihood of me being in the wrong is higher than usual.

1) Remark at the end of Section 1.1., part (b): usefull →‎ useful (multiple occurrences)
2) Definition 1.2.2.: alle →‎ all
3) occuring →‎ occurring (multiple occurrences)
4) Proof of Proposition 1.2.1.: sucht that →‎ such that
5) Proof of Corollary 1.2.1.: multipliying →‎ multiplying
6) Remark after Definition 1.2.3., part (b): that $g$ this →‎ that this $g$
7) Proof of Proposition 1.3.1., Step 2.: concernced →‎ concerned
8) Proof of Proposition 1.3.2., Step 3.: als →‎ also
9) Proof of Proposition 1.3.2., Uniqueness of tau: co-cartesianess →‎ co-cartesianness or cocartesianness (some would argue that co-Cartesianness is an even better spelling, but I don't really like it). There is inconsistency in the script regarding the usage of a hyphen in this word.
10) Example 1.4.1.(b): something seems to be wrong with the formula in the end.
11) Corollary 1.4.5.: sheafs →‎ sheaves
12) Definition 1.5.1.: ringend →‎ ringed
13) Remark after Fact 1.5.1.: if can →‎ it can
14) Definition 1.5.3.(a): Space →‎ space
15) Remark before Fact 1.5.7.: Prefessor →‎ \emph{Pre}fessor
16) Title of Chapter 2.: schmes →‎ schemes
17) Fact 2.1.1.(a): $U \subseteq X$ →‎ $U \subseteq Y$
18) Remark 2.1.2.: characteristized →‎ characterized (or characterised, but I guess you prefer the spelling with a z)
19) Fact 2.1.12.: weekend →‎ weakened
20) Proof of Corollary 2.2.3.: assings →‎ assigns
21) Proof of Lemma 2.2.12.: the Latin and Greek letters appear to have switched roles.
22) Fact 2.2.1.: locally of finite type →‎ of locally finite type
23) Beginning of Section 2.3.: woudn't →‎ wouldn't
24) Fact 2.4.1.: equvalent →‎ equivalent
25) Proof of Proposition 2.4.1.: Artin-Tate →‎ Artin--Tate (if I understood correctly, the theorem is not by a single person, Artin-Tate, but a result by Artin and Tate)
26) Definition 2.6.1.: $X \to Y$ →‎ $X \xrightarrow{f} Y$, whenever $A$ is closed in $Y$ →‎ whenever $A$ is closed in $X$
27) Example 2.6.3.: missing close-parenthesis in the 1st formula of the 4th sentence.
28) Remark 2.6.2.: I don't see the need for a hyphen in finitely-generatedness.
29) Remark before Definition A.2.2.: epismorphism →‎ epimorphism
30) Definition A.3.1.: morhism →‎ morphism

As always, thank you for the notes, they are really good.

**Comment by FlorianAdler** [comment]
Thanks, I fixed them (except for #19, that one is intentional ;) ).
