### ISSUE TITLE
typo regarding sheafification (AlgGeoI)

### ISSUE THREAD

**Issue by bforras** [Nicholas42/AlgebraFranke#16]
Hey, I think there is a typo in the AlgGeo I script, in part (a) of the Remark after Definition 1.2.3: gamma should be in G(V) instead of G(U).

**Comment by bforras** [comment]
Another typo: at the very end of the proof of Proposition 1.3.1, the verbs desire and satisfy seem to have switched roles (although this may have been intended as a pun).

**Comment by bforras** [comment]
Moreover, the A on the left hand side of (1) in Proposition 2.5.1 should be calligraphic. Also at the beginning of that subsection, in the description of the topology base one should probably write A_x instead of A_X.

**Comment by FlorianAdler** [comment]
Thx, fixed (except for the satisfied desire).
