### ISSUE TITLE
Remark after proposition 1.2.3 in HomAlg

### ISSUE THREAD

**Issue by BastiaanCnossen** [Nicholas42/AlgebraFranke#18]
In the remark following the proof of proposition 1.2.3 in Methods in Cohomological Algebra, you write "Remark. As the proof shows, (b) ⇒ (c) ⇒ (d) already holds when I is fixed."
I think the proof even shows the equivalences of these three points for fixed I and that this is also what Franke mentioned in the lecture (he used it to justify that we can simply restrict (b), (c) and (d) to only prime ideals I.)

**Comment by BastiaanCnossen** [comment]
Also in example 1.2.5 you write "M ⊗_R \hat{R} \cong \hat{R}", where I suppose you mean \hat{M} on the RHS.

**Comment by FlorianAdler** [comment]
Absolutely. Fixed, thanks.

**Comment by BastiaanCnossen** [comment]
[Edit] Okay I suppose my previous suggestion was wrong since otherwise Franke wouldn't have done it this way. But do you know why $0 = Tor1(k, M) \cong Tor1(M, k)$ only holds for all finitely generated R-modules M in the proof of corollary 1.3.2?
