### ISSUE TITLE
colimits commute with colimits

### ISSUE THREAD

**Issue by willemdmk** [Nicholas42/AlgebraFranke#20]
In the appendix it is proven that colimits commute with colimits by explicit calculation. I would like to remark that this may be proven by the fact that colimits are a left adjoint to the diagonal functor and hence commute with colimits.

**Comment by FlorianAdler** [comment]
That's really nice! I wasn't aware of that -- when I wrote this proof I just tried to formulate something that is true and proves what I need. Changed now.
Thanks!
