### ISSUE TITLE
Question lemma 2.3.3

### ISSUE THREAD

**Issue by BastiaanCnossen** [Nicholas42/AlgebraFranke#23]
Hi,
To start: there are three typos in this lemma: the final r^{-k} should be \lambda^{-k}, you wrote J(dk+n) instead of J_X(dk+n), and I think you mean a section of J_X{dk+n} over Y instead of over U. 
Apart from that, I don't really understand the argumentation of the proof. Why does the definition of I imply that gamma_k = g \lambda^k \in I_{dk+n}? Thanks for helping me out!

**Comment by FlorianAdler** [comment]
Fixed the typos. The argument is explained in more detail now, I hope this clears things.
