### ISSUE TITLE
HomAlg typos

### ISSUE THREAD

**Issue by bforras** [Nicholas42/AlgebraFranke#24]
Here is a list of typos in the HomAlg script. I'm preparing for the exam in the next few days so there might be more to come—perhaps you should consider keeping this thread open for a while. I included some non-typo-related remarks which you should feel free to ignore. Of course, your notes are excellent as usual—I'm utterly grateful to you for providing them to us.

* Proof of Proposition 1.1.1: m \in M'\setminus Q_*
* Corollary 1.1.1(a): equivalent to divisibility
* Fact 1.1.7: a bullet is missing
* Definition 1.2.2: with these properties (or is this a grammatical way of calling one's attention to the fact that these properties are actually the same?)
* Definition 1.2.3: no comma necessary after -\infty
* Definition A.1.1: in the last paragraph of the definition, that is, when defining right-derived functors, F needs to be left-exact. Moreover a right-derived functor is cohomological. (I guess these errors are due to copy-pasting the previous paragraph.)
* Proof of Definition A.1.2: It may very well be that I'm blind, but I fail to see where \alpha was defined. I guess it is the composition pi in the displayed formula.
* Proof of Theorem A: when proving independence of \iota and naturality of \alpha^n, we want to show \Psi^n(\xi) \alpha^n_{X,\iota} = \alpha^n_{Y,\kappa} \Phi^n(\xi). (In the script, \Psi is written on both sides.)
* One should be aware that Professor Franke is fond of using the English word “when” in a way as one would use the German word “wenn”. A prominent example is writing something like “When (condition), then (statement)”, similarly to how one would do in German: “Wenn (condition), dann (statement)”. In such cases, it is advisable to either change the “when” to an “if” or omit the word “then”.

**Comment by bforras** [comment]
I'm still using the version of the script from 14 July—if any of the following have been corrected in today's version I apologise.
* Proof of Theorem A, if part of b), second cubic diagram: on the front face, the top right and bottom right node should have X' instead of X. Also there is an extra “a” on one of the vertical arrows.
* Proof of Theorem A, if part of b), uniqueness of \alpha: one should have X' in the short exact sequence instead of X''.
* Proof of Theorem A, part a): R^pF(f) = H^p(Ff^\*) instead of H^p(f^\*).
* Proof of Theorem A, part a): caveat! Y and Z are in reversed roles here and in the horseshoe lemma. 
 I^\bullet_Y should be changed to I^\bullet_Z and vice versa. (Of course, this problem could be remedied more easily by taking 0→X→Z→Y→0 instead of 0→X→Y→Z→0 but I don’t like abusing lexical order like that.) Additionally, the second R^pF(X) in diagram (#) should be R^pF(Z).
* Aren’t we choosing the kappas using part a) of the horseshoe lemma instead of part b)? In the next paragraph, we use part b) (and not a)) to see that the maps in question are cochain homotopic.
* As far as I know, “safe for” is incorrect and one should use “save for” instead.

**Comment by bforras** [comment]
Typos in the proof of the horseshoe lemma:
* Towards the end of part a): on two occasions one should write d^{n-1}_I instead of d^n_I, both of these typos occur in the same sentence.
* After the displayed equations, it is only the moprhism in parentheses that factors over the cokernel, i.e. there is an extra d^{n-1}_I.
* Part c): We get \delta^0 such that d_I^0\hat\xi=\delta^0\beta, i.e. no upsilon is necessary. In the next paragraph, one should generalise the formulae copied from the case k=0: we have d_I^k \hat d_I^{k-1}=d^k j^{k-1} and d_K^k \zeta=0 where \hat d_I^{k-1} is defined in the same fashion as \hat\xi, that is, using the fact that i^k is mono.

**Comment by FlorianAdler** [comment]
Thanks a lot. I'm afraid, correcting these typos will have to wait some time since I'll be on the IMC in Bulgaria next week.

**Comment by bforras** [comment]
* Proof of Corollary 1.1.6: moduls → modules
* In the elaboration on completion, shouldn’t the inclusion coming from Artin–Rees be in the other direction?
* Fact 1.2.2(b): functoriality of Tor, not Ext
* Proof of Proposition 1.2.3: fewer than

Good luck on the IMC!

**Comment by bforras** [comment]
* In section 2.1, cohomology needs to be changed to homology in formulae quite a few times in the proof of Proposition 1, the Remark after that and in the proof of Fact 1.
* Section 2.2, after the 2nd displayed equation: equals its length.
* Proof of Proposition 2.3.1: it is supp T that is supposed to be {m}, not supp M. Moreover, there is no Lemma 3.1.4 in the Algebra II script.

**Comment by bforras** [comment]
Here are some more. I’m done with the exam now so this is the final list. I tried my best not to include any issue more than once. Good luck to everyone on the exam!
* Proof of Proposition 1.1.1: M and M' are switched up in the displayed formula and the paragraph that follows.
* Lemma 1.1.1(c): an abelian group.
* Definition of truncations of cochain complexes: perhaps one should emphasise that we do not have isomorphisms to the images in general. Of course we only care about the case when the complex is an injective resolution, and then the isomorphism indeed holds.
* Proof of Corollary 1.1.6: When M is torsion-free. Moreover, in the last formula we have that the projective dimensions are \le 0.
* Remark after Corollary 1.1.7: becomes.
* Before Proposition 1.2.1: follows.
* Proposition 1.2.3: I feel to need to recall that when Professor Franke suggested one should look up the statement in Matsumura he used the words “as a punishment”—and may I add that it seemed like he found this genuinely amusing. This has nothing to do with typos but I believe that such an occasion should be remembered in as much detail as possible. :)
* Fact 1.2.7(f): any.
* Corollary 1.3.1: the same as the perhaps intentional typo in Definition 1.2.2 in the original post
* Proof of Lemma 1.3.1: the m_i generate M as an R-module.
* Corollary 1.3.4: the letter (d) is overloaded. In the proof, one of the letters should be changed to (c).
* Section 2.1: it appears that while in Algebraic Geometry II, the variables of the Koszul complex are indexed from 0, in this lecture Professor Franke chose to start the indexing from 1. Some of the formulae in this section use indexing starting at 0.
* Proof of Corollary 2.1.1, end of part (a): H_1(x,M)=0.
* Beginning of Section 2.2: the direct sum in the definition of the associated graded ring should have upper limit infinity.
* Proof of Theorem 1, just after ($): the right term in the short exact sequence should be R/xR.
* Proof of Theorem 2, between (*) and ($): Ext_R^{p+1}(M, –).
* Lemma 2.3.1: Ext_R^0(k, M).
* Construction of Ext: before the first displayed formula, in the short exact sequence one either has to switch X' and X'' or consider the opposite category (as this is indicated later).

**Comment by FlorianAdler** [comment]
I finally found the time to work through your list. I hope I corrected each mistake you pointed out ... except for

> Proof of Theorem 1, just after ($): the right term in the short exact sequence should be R/xR.

I _really_ think m/xR is correct here.

Many thanks again for taking the time to point out ~this~ these errors.
Best wishes
Ferdinand
