### ISSUE TITLE
Some typos in script Algebra I

### ISSUE THREAD

**Issue by BastiaanCnossen** [Nicholas42/AlgebraFranke#3]
Hi guys,

First, big compliments for the great script that you have written of the course!!! It is incredibly helpful for new students that want to find out what Algebra I was about. So thanks a lot!!

Here are some typos I found on the script while reading, and sometimes also some suggestions that will improve readability:
- P1. A comma might be placed in the first sentence, to distinguish the intended 'the course Algebra I, taught in Bonn...' from the interpretation 'the course Algebra that I taught in Bonn...'
- P2. Although professor Franke himself probably used "I" both as an index set as well as an ideal, it might be useful to change the notation of the index set. (I don't think it would lead to confusion to anyone, but come on... we're mathematicians right? We don't want ambiguity... ^^)
- P13. What does the remark mean? It seems like there is no f that can be taken, and since Theorem 2 is the Nullstellensatz, the remark is confusing since it was used in the proof. If an equivalence of the two statements is meant, maybe an extra sentence can be used to explain that.
- P16. In the middle of the proof of proposition 16, in the sentence starting with "Now let A be any", I would suggest more emphasis on the fact that the non-empty subset U of Y must be \emph{open} by replacing "non-empty subset U" by "non-emtpy open subset U".
- P18. (Irrelevant) it's "an irreducible" instead of "a irreducible" in the proof of prop. 3
- P20. (Important!) At the very top of the page, the double restrictions of f should use U_{\gamma} \cap U_{\vartheta} for the second restriction.
- P22. At the middle of the page, in the sentence starting with "Since X = ...", V(p) should be used instead of V(q).
- P22. In the final equation of the proof of proposition 2, near the bottom of the page, the factor q_j(x) in front of the first sum should be removed and the factor a_ip_i should be replaced by a_iq_i.
- P23. In the correspondence, we now have "A \subseteq k^n" here, and no longer "A \subseteq X".
- P23. In the proof of fact 1, \overline{X} should be a subset of k^n instead of an element.
- P23. At the very bottom of the page, on the right, f_i^{-1}(V) should be f^{-1}(V).
- P29. At the top of the page, it might be didactically wise to change the f in the mentioned bijection to a \varphi, since in the equivalent formulation given afterwards, the f plays a different role, and the \varphi plays the role of the map previously denoted f. 
- P32. The intersection in (a) of fact 1 doesn't have an argument.
- P37. In point (\beta) of the proof of (e) of corollary 1, the comment (and b \in q) should be replaced by (and b \in p). 
- P41. At the very top of the page, at the end of the line, you do in fact want to say "and dim(k^n) \leq n by Corollary 1."
- P42. In (a) of definition 1, the \tilde(p) and p should be switched, so it should be p = f^{-1}(\tilde{p}) instead of the other way around. 
- P42. In (b) of definition 1, the final q should be a \tilde{q}.

Yeah I know it was a long list, and you might be wondering why I took the trouble to write this all down, but I think a few of these typos could lead to confusion and would be good to be shared with you, so then I decided I might just as well mention the other ones too.
I hope this was useful!

Kind regards,
Bastiaan

**Comment by Nicholas42** [comment]
Hi Bastiaan,

thanks for your input. We really appreciate, that you took the trouble to write this down, so that we can further improve our notes. We think we fixed everything in one of the last commits.

Best wishes,
Nicholas
