### ISSUE TITLE
irreducible sets

### ISSUE THREAD

**Issue by ghost** [Nicholas42/AlgebraFranke#6]
Being irreducible is a property of a topological space. The definition should look like $X$ (a topological space) is irreducible, if for any closed subsets $A$ and $B$ with $A \cup B = X$, it follows that $A = X$ or $B = X$.

Now you remark at several points, that there is a confusion with the definition of irreducible, at some point with some additional assumption of closedness. Here I am even more confused. Did Franke define irreducible with $A$ and $B$ not necessarily closed subsets (in the formulation above)?

I guess, part of the confusion comes from the following: It makes no sense to ask a topological space to be closed (Where should it be closed in anyway? In itself, it is always closed..). But there is another (or there are two other) notions of "relative irreduciblity", that is, an irreducible subspace of a topological space $X$ is a closed subset $Z$, which is irreducible in the above sense. Here one can ask for the additional condition that $Z$ is closed. But one can also drop this condition and say that an irreducible subspace is a subset $Y$, which, with the induced topology, is an irreducible topological space.

I didn't go through all your skripts (and I don't attend the lectures), but you should keep this in mind; or at least explain, what you mean.

By the way, in this relative irreducibility it makes sense to assume that the subspace is closed. In fact, the irreducible components of a variety (or more generally a finite type scheme over a field) are  exactly the maximal closed and irreducible subspaces. Probably the definition of irreducible subspace to be closed and irreducible makes sense, as one wants to consider these anyway.

**Comment by Nicholas42** [comment]
We were aware of this possible point of confusion. It stems from Franke's way of talking about irreducible subsets. He defined the irreducibility of an topological space and that a subset is called irreducible, if it is irreducible as the space with the induced topology, as you wrote in the issue. In Algebra I he goes on and says, that he wants to use the term "irreducible" as a short form of "irreducible closed". We tried to make it clearer in the notes and hope that it is now less confusing.

Thank you for writing this issue and the long explanation. @kes021
